name: CI

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - run: pip3 install black
    - run: python3 -m black .
    - run: git --no-pager diff --exit-code HEAD

  export:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Install inkscape and imagemagick
      run: |
        sudo add-apt-repository ppa:inkscape.dev/stable
        sudo apt-get update -q
        sudo apt-get install inkscape imagemagick -y
    - run: ./export.py
    # Ignore .svg files because Ubuntu 22.04 inkscape has round-off issues and
    # .ico files because Ubuntu 22.04 ImageMagick gives different results
    - run: git --no-pager diff --exit-code HEAD -- . ':!export/ico' ':!export/svg'

  generate-icns:
    runs-on: macos-14
    needs: export
    steps:
    - uses: actions/checkout@v4
    - name: Generate ICNS
      run: |
        mkdir -p wpilib-icon.iconset
        cp export/png/wpilib-icon-16.png   wpilib-icon.iconset/icon_16x16.png
        cp export/png/wpilib-icon-32.png   wpilib-icon.iconset/icon_16x16@2x.png
        cp export/png/wpilib-icon-32.png   wpilib-icon.iconset/icon_32x32.png
        cp export/png/wpilib-icon-64.png   wpilib-icon.iconset/icon_32x32@2x.png
        cp export/png/wpilib-icon-128.png  wpilib-icon.iconset/icon_128x128.png
        cp export/png/wpilib-icon-256.png  wpilib-icon.iconset/icon_128x128@2x.png
        cp export/png/wpilib-icon-256.png  wpilib-icon.iconset/icon_256x256.png
        cp export/png/wpilib-icon-512.png  wpilib-icon.iconset/icon_256x256@2x.png
        cp export/png/wpilib-icon-512.png  wpilib-icon.iconset/icon_512x512.png
        cp export/png/wpilib-icon-1024.png wpilib-icon.iconset/icon_512x512@2x.png
        iconutil -c icns wpilib-icon.iconset
        cp wpilib-icon.icns export/icns
    - uses: actions/upload-artifact@v4
      with:
        name: wpilib-icon.icns
        path: wpilib-icon.icns
    - run: git --no-pager diff --exit-code HEAD -- . ':!export/ico' ':!export/svg'
